version: '3.8'

services:
  app:
    container_name: beautify
    build: .
    ports:
      - "9000:9000"
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
      DATABASE_URL: ${DATABASE_URL}
      PORT: ${PORT}
      SECRETKEY: ${SECRETKEY}
      EXPIRESIN: ${EXPIRESIN}
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_USER: ${MAIL_USER}
      MAIL_PASS: ${MAIL_PASS}
      NOTCHPAY_PUBLIC_KEY: ${NOTCHPAY_PUBLIC_KEY}
      NOTCHPAY_PRIVATE_KEY: ${NOTCHPAY_PRIVATE_KEY}
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root2025
      MYSQL_DATABASE: beautify
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
