name: Top Nyanga Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: SSH into VPS and deploy
      uses: appleboy/ssh-action@v0.1.0
      with:
        host: ${{ secrets.VPS_IP }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          cd /var/www/topnyanga
          git pull origin main
          npm install
          npm run build
          pm2 restart topnyanga
